resolver: lts-24.31

packages:
  - .

extra-deps:
  - shakespeare-sass-0.1.4.1

  # Fix nix build
  # > System/Process/Environment/OsString.hs:15:1: error: [GHC-61948]
  # >     Could not find module ‘System.OsString.Internal.Types’.
  # >     Perhaps you meant
  # >       System.OsString.Internal.Types (needs flag -package-id os-string-2.0.7)
  # >       System.OsString.Internal (needs flag -package-id os-string-2.0.7)
  # >       System.OsString.Internal.Exception (needs flag -package-id os-string-2.0.7)
  - process-1.6.26.1
flags:
  process:
    os-string: true

allow-newer: true
allow-newer-deps:
  - shakespeare-sass
