version: "2.2"
services:
  postgres:
    image: postgres:10.3
    env_file: ./database/dev_env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
    
