version: "2.2"
services:     
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - twenty48
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
